config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'gossip_controller#index', as: "home"
  get 'gossip/:id', to: 'gossip_controller#show_gossip'
	get 'welcome/:first_name', to: 'dynamic_pages#welcome'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get 'author/:user_id', to: 'author#show_author', as: 'author'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users, dependent: :destroy
	validates :name, presence: true
	validates :zip_code, 
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[abAB]))[0-9]{3}\z/, message: "good zip code please" }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, dependent: :destroy
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :tags, through: :join_table_tag_gossips, dependent: :destroy
	validates :title, presence: true
  validates :content, presence: true
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
	belongs_to :tag
  belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
	validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_tag_gossips, dependent: :destroy
	has_many :gossips, through: :join_table_tag_gossips, dependent: :destroy
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city, dependent: :destroy
	has_many :gossips, dependent: :destroy
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "Message", dependent: :destroy
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "Message", dependent: :destroy

	validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

  validates :first_name, presence:true

  validates :last_name, presence:true

  validates :description, presence:true

  validates :age, presence:true

  validates :city, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def show_author
    @user = User.find(params["user_id"])
  end
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def welcome
  	@first_name = params["first_name"]
  	
  end
end

app/controllers/gossip_controller_controller.rb
class GossipControllerController < ApplicationController
  def index
  	@all_gossip = Gossip.all
  end

  def show_gossip
  	puts "@"*30
  	@all_gossip = Gossip.all
  	@gossip_number = params["id"]
  	@gossip_identity = @all_gossip[params["id"].to_i]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_controller_helper.rb
module GossipControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/author/show_author.html.erb
<div class="container-fluid">
	<div class="card text-center mt-3">
	  <div class="card-header">
	    <h1>Espace de <%= @user.first_name %> <%= @user.last_name %></h1>
	  </div>
	  <div class="card-body">
	    <h5 class="card-title">Description : <span class="font-italic"><%= @user.description %></span></h5>
	    <p class="card-text"><%= @user.first_name %> a <%= @user.age %> ans et habite <%= @user.city.name %>. Contactez cet auteur à l'adresse email suivante : <%= @user.email %></p>
	  </div>
	</div>


	<div class="row mt-3">
		<% @user.gossips.each do |gossip| %>
			<div class="card mx-auto mb-5" style="width: 30rem;">
			  	<div class="card-body">
			    <h5 class="card-title"><%= gossip.title %></h5>
			    <p class="card-text"><%= gossip.content %></p>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/dynamic_pages/welcome.html.erb
<div class="container-fluid">
	<div class="card text-center mt-3">
	  <div class="card-header">
	    <h1>Welcome <%= @first_name %>!</h1>
	  </div>
	  <div class="card-body">
	    <p class="card-text">Ici c'est notre super site de potins, il est chouette, non ?</p>
	  </div>
	</div>
</div>

app/views/gossip_controller/index.html.erb
<div class="container-fluid">
	<h2 class="d-flex justify-content-center mt-3">Bienvenue sur The Gossip Project</h2>
		<div class="row mt-3">
			<% @all_gossip.each_with_index do |gossip, i| %>

					<div class="card mx-auto mb-5" style="width: 15rem;">
			  			<div class="card-body">
			    		<h5 class="card-title"><%= gossip.user.first_name %> <%= gossip.user.last_name %></h5>
			    		<p class="card-text"><%= gossip.title %></p>
			    		<a href="/gossip/<%= i%>" class="btn btn-primary">Voir le potin</a>
			  			</div>
					</div>

			<% end %>
		</div>

</div>

app/views/gossip_controller/show_gossip.html.erb
<div class="container-fluid">
	<div class="card text-center mt-3">
	  <div class="card-header">
	    <h1> Gossip numéro <%=@gossip_number%></h1>
	  </div>
	  <div class="card-body">
	    <h4 class="card-title"><%= @gossip_identity.user.first_name %> <%= @gossip_identity.user.last_name %> </h4>
	    <h5 class="card-title"><%= @gossip_identity.title %></h5>
	    <p class="card-text"><%= @gossip_identity.content %></p>
	    <%= link_to "Profil de l'auteur", author_path(@gossip_identity.user.id), :class => "btn btn-primary" %>
	  </div>
	  <div class="card-footer text-muted">
	    Date de création : <%= @gossip_identity.created_at.strftime("%d/%m/%Y") %> 
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "THE GOSSIP PROJECT", home_path, :class => "navbar-brand"%>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Team", team_path, :class => "nav-item nav-link"%>
          <%= link_to "Contact", contact_path, :class => "nav-item nav-link"%>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/contact.html.erb
<section>
      <div class="container-fluid p-3 mb-2 bg-info text-white">
        <br /><h2>Venez nous voir à la Felicita de la Station F !!!</h2><br />
        <p> Travailleurs infatigables fonctionnant au café, nous sommes dans les locaux de 9h30 à 19h (au moins...) du lundi au vendredi jusqu'à fin mars!!!</p><br />
        <p> Si vous n'habitez pas Paris, retrouvez nous sur Slack : Viviane de Pétigny (@viviane de petigny), bastien Hiel (@bastien hiel), Alexis Janin (@alexdji)</p><br />
      </div>
   </section>

app/views/static_pages/team.html.erb
<section>
    <div class="container">
      <div class="row">
        <div class="col-sm d-flex flex-column align-items-center"><br />
        <i class="fas fa-user-circle fa-5x"></i><br />
        <h2>Viviane</h2>
        <p class=text-justify>24 ans, Paris, dictateur en chef et diplomate en herbe. Craqueurs de doigts, s'abstenir... (à vos risques et périls...)</p><br />
        </div>
        
        <div class="col-sm d-flex flex-column align-items-center"><br />
        <i class="fas fa-user-circle fa-5x"></i><br />
        <h2>Bastien</h2>
        <p class=text-justify>27 ans, Paris, développeur ruby. Passionné de Rocket League, recrute partenaire potentiel..(débutants bienvenus!!!)</p><br />
        </div>
        
        <div class="col-sm d-flex flex-column align-items-center"><br />
        <i class="fas fa-user-circle fa-5x"></i><br />
        <h2>Alex</h2>
        <p class=text-justify>24 ans, Paris, inspecteur des travaux finis. Passioné de pétanques et de complots, j'anime vos conversations de cafés et bars. </p><br />
        </div>
      </div>
    </div>
</section>